server:
 port: 7077
 servlet:
  session:
   # 以秒为单位，这里设置为1h
   timeout: 3600
   cookie:
    # -1  浏览器关闭后立即将cookie清除
    # 0   立即将cookie清除
    # x   x秒后将cookie清除
    max-age: -1
    name: sb-id

spring:
 resources:
  # 资源路径，可以通过http://xxx:xxxx/xxx.png直接访问资源
  static-locations:
   - classpath:/static
 # 配置String到View的映射
 # prefix和suffix表示将xxx.html放在/templates/文件夹下，当Controller返回xxx时thymeleaf就可以自动渲染
 thymeleaf:
  prefix: classpath:/templates/
  suffix: .html
  # 关闭缓存
  cache: false
 servlet:
  multipart:
   max-file-size: 1024000000
   max-request-size: 4096000000
 datasource:
  url: jdbc:mysql://localhost:3306/sleepy?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  password: 1994
 redis:
  host: 127.0.0.1
  port: 6379
  database: 0
 main:
  allow-bean-definition-overriding: true
 session:
  store-type: redis

mybatis:
 mapper-locations: classpath:/mappers/*.xml

logging:
 level:
  root: info
